# Generated by Django 2.2.7 on 2019-11-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='starring',
        ),
        migrations.AddField(
            model_name='title',
            name='starring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='starrings', to='ratings.Starring'),
            preserve_default=False,
        ),
    ]
