# Generated by Django 2.2.7 on 2019-11-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20191123_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='gender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='ratings.Gender'),
        ),
    ]
