# Generated by Django 2.2.7 on 2019-11-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20191123_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='starring',
            name='nationality',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='ratings.Gender'),
        ),
    ]
