# Generated by Django 2.2.7 on 2019-11-23 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20191123_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='ratings.Gender'),
        ),
    ]
