# Generated by Django 2.2.7 on 2019-11-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20191123_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rate',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='average',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
