# Generated by Django 2.2.7 on 2019-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_remove_title_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
