# Generated by Django 2.2.7 on 2019-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_title_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='average',
        ),
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
