# Generated by Django 2.2.7 on 2019-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_auto_20191208_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='review',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
